//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OidcProxy.Net.Okta.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OidcProxy.Net.Okta.Tests.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN CERTIFICATE-----
        ///MIIDdTCCAl2gAwIBAgIUD6JVoIkWN8azylh7P7vtGdfKsAkwDQYJKoZIhvcNAQEL
        ///BQAwSjELMAkGA1UEBhMCTkwxCzAJBgNVBAgMAlVUMQswCQYDVQQHDAJVVDEhMB8G
        ///A1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMB4XDTI0MDIxMjE4NTkyOFoX
        ///DTM0MDIwOTE4NTkyOFowSjELMAkGA1UEBhMCTkwxCzAJBgNVBAgMAlVUMQswCQYD
        ///VQQHDAJVVDEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjAN
        ///BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6P5WqktFjQ3+iZU/51cwJD0XJXFU
        ///0e2t29wCt8TN7hHPhXGofjDcuMyLi3r6EiluMI1rwxyjJhMqbfxybDn6NIaj0NT+
        ///8A1JA/2Stwv42O8MEcJQD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cert {
            get {
                return ResourceManager.GetString("Cert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PRIVATE KEY-----
        ///MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDo/laqS0WNDf6J
        ///lT/nVzAkPRclcVTR7a3b3AK3xM3uEc+Fcah+MNy4zIuLevoSKW4wjWvDHKMmEypt
        ////HJsOfo0hqPQ1P7wDUkD/ZK3C/jY7wwRwlANc3OHy56NewpQXY6hMQrmmXHj2ZkD
        ///fTERZMv83lYXt5XwOGqGjSeb/Gj2i5Mbd1+4/F5vz12kH2HR2tz/CTv5wiswIMAB
        ///xPBzHqyktKAhCsqdMvHjN2z8rQ9sKw4oZkbXIkNHAmOHkhbTPK1CLd/mZ607Wgow
        ///UuwU2imM+1nwrTqcPZ5j1cvDtk/SErS8EVw64dvwCxUl372OvBiRIxQPEjVg31aF
        ///IjFzVBR9AgMBAAECggEAIKrp3NZRSfiLK/WMsF4wUPcYeTaoMAegB60T289Qw6Sk
        ///pkRW3bFH0/NTTNBbzVMYx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
    }
}
